# Generated by Django 4.1 on 2022-09-08 05:24

import contents.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_image', models.ImageField(upload_to=contents.models.product_images_url, verbose_name='상품 이미지')),
                ('product_name', models.CharField(max_length=255, verbose_name='상품명')),
                ('product_price', models.IntegerField(verbose_name='가격')),
                ('product_condition', models.CharField(choices=[('중고', 'Used'), ('새상품', 'New')], max_length=20, verbose_name='상품상태')),
                ('exchange_or_not', models.CharField(choices=[('교환불가', 'Non Exchangeable'), ('교환가능', 'Exchangeable')], max_length=20, verbose_name='교환여부')),
                ('trading_location', models.CharField(max_length=50, verbose_name='거래 지역')),
                ('product_desc', models.TextField(verbose_name='상품 정보')),
                ('product_count', models.IntegerField(verbose_name='수량')),
                ('product_category', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='product_category_set', to='contents.category')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_product_set', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProuctImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to=contents.models.product_images_url, verbose_name='상품 이미지')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='contents.products')),
            ],
        ),
    ]
