# Generated by Django 4.1 on 2022-09-08 10:39

import contents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_product_productimage_remove_prouctimages_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=contents.models.product_images_url, verbose_name='상품 이미지'),
        ),
    ]
