# Generated by Django 4.1 on 2022-09-09 15:08

import contents.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_alter_productimage_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_image',
            field=models.ImageField(upload_to=contents.models.product_images_url),
        ),
    ]
