# Generated by Django 4.1 on 2022-09-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_rename_product_id_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='writer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
