# Generated by Django 4.1 on 2022-09-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_productimage_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='writer',
            field=models.TextField(),
        ),
    ]
