# Generated by Django 4.1 on 2022-09-20 05:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_like',
            field=models.ManyToManyField(blank=True, related_name='like_product_set', to=settings.AUTH_USER_MODEL, verbose_name='찜'),
        ),
    ]
