# Generated by Django 4.1 on 2022-09-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0010_product_product_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_views',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
    ]
