# Generated by Django 4.1 on 2022-09-20 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0011_product_product_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_views',
        ),
        migrations.AddField(
            model_name='product',
            name='product_views',
            field=models.ManyToManyField(blank=True, related_name='view_product_set', to=settings.AUTH_USER_MODEL, verbose_name='조회수'),
        ),
    ]
