# Generated by Django 4.1.2 on 2022-10-19 07:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0012_remove_product_product_views_product_product_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_like',
            field=models.ManyToManyField(blank=True, related_name='product_like', to=settings.AUTH_USER_MODEL, verbose_name='찜'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_views',
            field=models.ManyToManyField(blank=True, related_name='product_views', to=settings.AUTH_USER_MODEL, verbose_name='조회수'),
        ),
    ]
