version: "3.9"

services:
  market_db:
    image: mysql:latest
    restart: always
    volumes:
      - D:/a_KGN/usedMarket/data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=market
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:33060"

  api:
    build: ./api
    restart: always
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - D:/a_KGN/usedMarket/api:/back
    environment:
      - MYSQL_HOST=market_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_NAME=market
      - MYSQL_DB=market
    depends_on:
      - market_db

  client:
    build: ./client
    command: npm start
    volumes:
      - D:/a_KGN/usedMarket/client:/front
      - D:/a_KGN/usedMarket/client/node_modules:/front/node_modules
    depends_on:
      - api

  web:
    restart: always
    container_name: nginx
    build: ./nginx
    volumes:
      - D:/a_KGN/usedMarket/api/static:/back/static
      - D:/a_KGN/usedMarket/api/media:/back/media
    ports:
      - "8000:8081"
      - "3000:8080"
    depends_on:
      - api
      - client

  redis:
    image: redis:6
    environment:
      - REDIS_HOST=client_web
      - REDIS_PORT=6379

    ports:
      - "6379:6379"
