version: "3.9"

services:
  market_db:
    image: mysql:latest
    restart: always
    volumes:
      - D:/a_KGN/usedMarket/data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=market
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:33060"

  api:
    build: ./api
    restart: always
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - D:/a_KGN/usedMarket/api:/back
      - static_volume:/back/static

    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=market_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_NAME=market
      - MYSQL_DB=market
    depends_on:
      - market_db

  client:
    build: ./client
    command: npm start
    volumes:
      - D:/a_KGN/usedMarket/client:/front
      - D:/a_KGN/usedMarket/client/node_modules:/front/node_modules
    depends_on:
      - api

  client_web:
    restart: always
    container_name: nginx_client
    build: ./nginx/client
    ports:
      - "8080:80"
    depends_on:
      - client

  api_web:
    restart: always
    container_name: nginx_api
    build: ./nginx/api
    volumes:
      - static_volume:/back/static
    ports:
      - "8081:80"
    depends_on:
      - api
volumes:
  static_volume: